### ISSUE TITLE
Tweets don't load up in Simulator

### ISSUE THREAD

**Issue by njokusomto** [eh3rrera/twitter-feed-pusher#1]
Hi, I followed through from the tutorial on the Pusher website.

Everything seems correctly configured and runs properly.
Even the tweets show up in terminal but never come up on the simulator.

Is there something I'm missing?

**Comment by eh3rrera** [comment]
Hi @njokusomto,

- Did you replace your Pusher key in the method `viewDidLoad` of `ViewController`?
- If you go to the debug console in your [Pusher Dashboard](https://dashboard.pusher.com/), can you see when the client (iOS simulator) connects to Pusher?
- If you send an object to the client with this debug console, is it received?

Is hard to say where's the problem without looking at your code, can you upload it somewhere so I can take a look?

**Comment by njokusomto** [comment]
Hey @eh3rrera,

- I have my Pusher key in the ViewController.swift file.
- No, I can't see when the simulator connects to Pusher in the Pusher Dashboard
- Nope.

You'll find the code here:
https://filetea.me/n3wFHYqbOMxQu6bgsXvU4fhog

Looking to hear from you!

**Comment by eh3rrera** [comment]
The link throws an HTTP ERROR 404.

Another question, did you create your Pusher app in a cluster other than US? Because if you did you must provide the cluster when creating the Pusher instance.

**Comment by njokusomto** [comment]
> Another question, did you create your Pusher app in a cluster other than US? Because if you did you must provide the cluster when creating the Pusher instance.
Ah, I think that's where the problem is. I created it in an EU cluster. How do I add it to the Pusher instance?

You can download the code here.
https://www.dropbox.com/s/lrugqs92musy2vg/CM%2017%20Updates.zip?dl=0

**Comment by eh3rrera** [comment]
It should be something like:
```swift
let options = PusherClientOptions(
  host: .cluster("eu")
)

pusher = Pusher(
  key: "<YOUR_KEY>",
  options: options
)
```

I think is not required, but in the node.js app you can also add the cluster option to the config object:
```javascript
pusher: {
  cluster: 'eu',
},
```
You can find sample code in the **Getting Started** tab on your [dashboard](https://dashboard.pusher.com/). If the cluster is in US, this option is not required, but it is for the others (ap1 for Singapore, ap2 for India, and eu for Ireland).

This must be the error, I don't see anything wrong in your code.

**Comment by njokusomto** [comment]
Yep. The cluster was definitely the issue.
Added it to the instance and everything ran smoothly.

Is there a way I could replicate this but for select usernames and not hashtags?
That would really do it for me to use this in a practical setting.

Cheers!

**Comment by eh3rrera** [comment]
Great, I'll make sure to mention this in future tutorials to avoid confusions.

I believe you can. I haven't done this myself, but I think instead of using `track` in the node.js process:
```javascript
const stream = T.stream('statuses/filter', { track: config.hashtagsToTrack });
```
You can use [follow](https://dev.twitter.com/streaming/overview/request-parameters#follow) with the user's ID (I'm not sure if you can get the ID or the tweets just with the username).

Or instead of `statuses`, use the [user stream](https://dev.twitter.com/streaming/userstreams) for the tweets of your user (the one who owns the API keys).

Check the documentation of the [Streaming API](https://dev.twitter.com/streaming/overview) and the [twit library](https://github.com/ttezel/twit).
